//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerAnalytics_dev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> UTID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
        public string ExistingPassword { get; set; }
        public string AcademicStatus { get; set; }
        public string EmploymentStatus { get; set; }
        public string JobTitle { get; set; }
        public string JobIndustry { get; set; }
        public string Institution { get; set; }
        public Nullable<System.DateTime> AnticipatedGraduationDate { get; set; }
        public string Major { get; set; }
        public string Message { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
